[project]
name = "pyfuture"
dynamic = ["version"]
description = ""
authors = [
    {name = "Zhan Rongrui", email = "2742392377@qq.com"},
]
dependencies = [
    "libcst>=1.1.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://pypi.org/project/pyfuture"
Repository = "https://github.com/zrr-lab/pyfuture.git"

[project.scripts]
pyfuture = "pyfuture.__main__:app"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pdm.dev-dependencies]
test = [
    "pytest",
    "converage",
]

[tool.pdm.version]
source = "scm"
write_to = "pyfuture/__version__.py"
write_template = "__version__ = '{}'"

[tool.pdm.build]
includes = ["pyfuture"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
