name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        target-version: [py39, py310, py311, py312]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout ğŸ“¦
      uses: actions/checkout@v3
    - name: Setup PDM ğŸ“¦
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.12"
    - name: Build package ğŸ‘·â€â™‚ï¸
      env:
        PDM_IGNORE_SCM_VERSION: ${{ github.ref_name }}
        PYFUTURE_TARGET: ${{ matrix.target-version }}
      run: |
        pdm install
        pdm build --no-isolation --no-sdist
    - name: Upload wheels ğŸ‘·â€â™‚ï¸
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  publish-release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
    steps:
    - name: Checkout ğŸ“¦
      uses: actions/checkout@v3
    - name: Download wheels ğŸ‘·â€â™‚ï¸
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist
    - name: Publish to PyPi ğŸš€
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        packages-dir: dist
        verbose: true
    - name: Publish GitHub Release ğŸ“
      uses: softprops/action-gh-release@v2
      with:
        name: "PyFuture Release ${{ github.ref_name }}"
        token: ${{ secrets.RELEASE_TOKEN }}
        generate_release_notes:
        files: |
          dist/*
